### ISSUE TITLE
Allow "Duplicate Civilizations" and "Duplicate Leaders" as options for draft

### ISSUE THREAD

**Issue by holmat** [jakezatecky/civ-drafter#28]
Hi! I love this drafter, its the best one I've seen so far. I just used it for a game I'm starting up.

It appears that by default the drafter does not implicitly allow Duplicate Civilizations with different leaders when it draws the leaders for everyone. I would recommend allowing that as a an optional check box.

My group plays with duplicate civilizations allowed, but everyone plays a unique leader. So, supporting this in the draft would be ideal, as it's a possible game setting. Along the same lines, duplicate leaders are allowed as a game setting, so I would recommend implementing that at the same time.

I noticed this when trying to create a game with 10 players, where player 9 and 10 only had the two expansions, and the rest of us had all the DLC. (We have a banlist of 8 leaders that have won prior games) It gave me a warning that not enough options were available. I marked those players as having all the dlc, then noticed the final draft had no duplicate civs.

Thanks again, and hope that makes sense! Happy to answer any questions.

**Comment by holmat** [comment]
For reference to recreate, our banlist is 

Germany
Russia
Brazil
Spain
Mansa Musa - Mali
Vietnam
Bull Moose Teddy Roosevelt
Hojo Japan

And set 8 players as having all dlc, and two additional as only having both expansions.

**Comment by jakezatecky** [comment]
Yeah, the drafter should probably support duplicate leaders as an option. Originally, it did, but I changed it to its current behavior after I realized the default behavior in Civ 6 was to exclude that.

**Comment by jakezatecky** [comment]
I added two new options. The application now supports the scenario your group uses.

However, for the second option (duplicate leaders), this application does not _quite_ align with the game. It would involve more effort than I would like to change the randomization process to allow the exact same leader and personality combination to appear multiple times. Instead, the second option just allows multiple personalities per leader (e.g., the two different Kublai Khans can appear when the option is checked).

This compromise should satisfy most users, and if someone really wants real leader duplication, I can add it at some other time.

**Comment by holmat** [comment]
That is amazing, thanks Jake and thanks for the great leader drafter!
