### ISSUE TITLE
Old script version is cached and no longer exists with update

### ISSUE THREAD

**Issue by mattcrwi** [jakezatecky/civ-drafter#43]
Today I tried to come back to the page to find it a loading spinner that stayed on the screen. Looking at the console I saw that the .js file failed to load. Deleting static file cache fixed the issue, and the new version of /assets/js/app-6b682681d8c5ff0f001f.js was retrieved.

Without dev tools users would have to delete their whole cache, deleting their saved settings. I am on firefox 121.

**Comment by jakezatecky** [comment]
If I understand correctly, the HTML file was cached, and thus pointed to a JS file that no longer existed? I migrated over to Cloudflare a couple of months ago to save on hosting costs. Unlike S3, it removes older assets on each build.

I may have to check why the HTML file is getting cached, when it should never be cached. There may also be some annoying confounding factor with the implementation of the Progressive Web App, as I use some library to handle the offline functionality and it's a bit of a black box to me.

**Comment by jakezatecky** [comment]
I think this should be resolved for future instances. Anyone who visited an older version of the website prior to this latest update may have to do CTRL + F5 several times before the service worker updates to pulling `index.html` from the network first. Then, on subsequent application updates, the service worker should always pull the latest `index.html` (which points to the latest/valid JavaScript files) first.

**Comment by matt-williams-sa** [comment]
Yes, you understood my issue correctly. Thanks for the update.

**Comment by mattcrwi** [comment]
Yes, you understood my issue correctly. Thanks for the update.

wrong account last time :)
