### ISSUE TITLE
Remember last settings

### ISSUE THREAD

**Issue by alexey-sinyuk** [jakezatecky/civ-drafter#6]
Use cookies to remember last settings

**Comment by jakezatecky** [comment]
While cookies could work, we can also remember settings through the use of `localStorage`, which circumvents GDPR. I have internally wrestled whether it makes more sense to do this on a URL level or on a persistent storage level.

**Comment by jakezatecky** [comment]
Feature added. I'll just assume people want this behavior unless someone specifically requests to disable it.
